<a href="https://colab.research.google.com/github/devdattatemgire/Data-Mining-Algorithms-/blob/main/K-Means/K_MEANS_EXPT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**STATIC** **1D**

In [ ]:
import statistics
import numpy as np
min = 999
k = int(input("Enter the value for k"))
D = [2,3,4,10,11,12,20,25,30]
dist = np.empty(shape=(int(len(D)),int(k)))
dist.fill(0)
# print(dist)
oldcent = []
newcent = []


clusters = [[] for _ in range(k)]
print(clusters)
for i in range(int(k)):
  oldcent.append(int(input("Enter the Centroid")))
print("oldcent: ",oldcent)
print("clusters: ", clusters)
while(newcent != oldcent):
    clusters = [[] for _ in range(k)]
    if all(element != 0 for element in newcent):
      oldcent = newcent.copy()
    for i in range(int(len(D))):
      for j in range(k):
       dist[i,j] = abs(D[i]-oldcent[j])
    print("Distance: ",dist)
    for i in range(int(len(D))):
      for j in range(k):
       if dist[i,j] < min:
        min = dist[i,j]
        index = j
        clusters[index].append(min)
    print("Clusters Array: ", clusters)
    for cluster in clusters:
      mean_value = statistics.mean(cluster)
      newcent.append(mean_value)
    print("newcent: ", newcent)

In [ ]:
import statistics
k = input("Enter the value for k")
D = [2,3,4,10,11,12,20,25,30]
C1 = []
C2 = []
m1old = 4
m2old = 12
m1new=m2new=0
while(m1new != m1old and m2new != m2old):
  C1 = []
  C2 = []
  if (m1new!=0):
    m1old=m1new
    m2old=m2new
  for i in D :
    s1 = m1old-i
    s2 = m2old-i
    if (abs(s1)<abs(s2)):
      C1.append(i)
    else :
      C2.append(i)
  print("C1:", C1)
  print("C2:",C2)
  m1new = abs(statistics.mean(C1))
  m2new = abs(statistics.mean(C2))

print(m1new)
print(m2new)

C1: [2, 3, 4]
C2: [10, 11, 12, 20, 25, 30]
C1: [2, 3, 4, 10]
C2: [11, 12, 20, 25, 30]
C1: [2, 3, 4, 10, 11, 12]
C2: [20, 25, 30]
C1: [2, 3, 4, 10, 11, 12]
C2: [20, 25, 30]
7
25


#**DYNAMIC** **1D**



In [ ]:
import statistics
import numpy as np

min_dist = 999
k = int(input("Enter the value for k"))
D = [2,3,4,10,11,12,20,25,30]
dist = np.empty(shape=(int(len(D)), int(k)))
dist.fill(0)

oldcent = []
newcent = []

clusters = [[] for _ in range(k)]
print(clusters)

for i in range(int(k)):
    oldcent.append(int(input("Enter the Centroid")))

print("oldcent: ", oldcent)
print("clusters: ", clusters)
count = 0
while newcent != oldcent:
    clusters = [[] for _ in range(k)]
    min_dist = 999
    if count != 0:
     oldcent = newcent.copy()
     print("oldcent: ", oldcent)
    newcent = []

    for i in range(int(len(D))):
        for j in range(k):
            dist[i, j] = abs(D[i] - oldcent[j])

    print("Distance: ", dist)

    for i in range(int(len(D))):
        min_dist = 999
        for j in range(k):
            if dist[i, j] < min_dist:
                min_dist = dist[i, j]
                index = j
        clusters[index].append(D[i])

    print("Clusters Array: ", clusters)

    for cluster in clusters:
        print("cluster: ",cluster)
        mean_value = statistics.mean(cluster)
        newcent.append(mean_value)
        print("newcent: ", newcent)
    count = count + 1

Enter the value for k3
[[], [], []]
Enter the Centroid2
Enter the Centroid3
Enter the Centroid4
oldcent:  [2, 3, 4]
clusters:  [[], [], []]
Distance:  [[ 0.  1.  2.]
 [ 1.  0.  1.]
 [ 2.  1.  0.]
 [ 8.  7.  6.]
 [ 9.  8.  7.]
 [10.  9.  8.]
 [18. 17. 16.]
 [23. 22. 21.]
 [28. 27. 26.]]
Clusters Array:  [[2], [3], [4, 10, 11, 12, 20, 25, 30]]
cluster:  [2]
newcent:  [2]
cluster:  [3]
newcent:  [2, 3]
cluster:  [4, 10, 11, 12, 20, 25, 30]
newcent:  [2, 3, 16]
oldcent:  [2, 3, 16]
Distance:  [[ 0.  1. 14.]
 [ 1.  0. 13.]
 [ 2.  1. 12.]
 [ 8.  7.  6.]
 [ 9.  8.  5.]
 [10.  9.  4.]
 [18. 17.  4.]
 [23. 22.  9.]
 [28. 27. 14.]]
Clusters Array:  [[2], [3, 4], [10, 11, 12, 20, 25, 30]]
cluster:  [2]
newcent:  [2]
cluster:  [3, 4]
newcent:  [2, 3.5]
cluster:  [10, 11, 12, 20, 25, 30]
newcent:  [2, 3.5, 18]
oldcent:  [2, 3.5, 18]
Distance:  [[ 0.   1.5 16. ]
 [ 1.   0.5 15. ]
 [ 2.   0.5 14. ]
 [ 8.   6.5  8. ]
 [ 9.   7.5  7. ]
 [10.   8.5  6. ]
 [18.  16.5  2. ]
 [23.  21.5  7. ]
 [28.  26.5 1

#**DYNAMIC** **2D**


In [ ]:
import statistics
import numpy as np
import math

min_dist = 999
k = int(input("Enter the value for k"))
D =  [(2, 3), (3, 5), (5), 8, (10, 12), (12, 15), (14, 18), (20, 22), (25, 30), (30, 35)]
dist = np.empty(shape=(int(len(D)), int(k)))
dist.fill(0)

oldcent = []
newcent = []

clusters = [[] for _ in range(k)]
print(clusters)

for i in range(int(k)):
    x, y = input("Enter two values: ").split()
    oldcent.append([int(x),int(y)])


print("oldcent: ", oldcent)
print("clusters: ", clusters)
count = 0
while newcent != oldcent:
    clusters = [[] for _ in range(k)]
    min_dist = 999
    if count != 0:
     oldcent = newcent.copy()
     print("oldcent: ", oldcent)
    newcent = []

    for i in range(int(len(D))):
        for j in range(k):
            # dist[i, j] = abs(D[i] - oldcent[j])
            dist[i, j] = math.dist(D[i],oldcent[j])

    print("Distance: ", dist)

    for i in range(int(len(D))):
        min_dist = 999
        for j in range(k):
            if dist[i, j] < min_dist:
                min_dist = dist[i, j]
                index = j
        clusters[index].append(D[i])

    print("Clusters Array: ", clusters)

    for cluster in clusters:
      print("cluster: ", cluster)
      x_sum = sum(point[0] for point in cluster)
      y_sum = sum(point[1] for point in cluster)
      mean_value_x = x_sum / len(cluster)
      mean_value_y = y_sum / len(cluster)
      newcent.append((mean_value_x, mean_value_y))
    print("newcent: ", newcent)
    count = count + 1

Enter the value for k3
[[], [], []]
Enter two values: 2 3
Enter two values: 3 5
Enter two values: 10 2
oldcent:  [[2, 3], [3, 5], [10, 2]]
clusters:  [[], [], []]
Distance:  [[ 0.          2.23606798  8.06225775]
 [ 2.23606798  0.          7.61577311]
 [ 5.83095189  3.60555128  7.81024968]
 [12.04159458  9.89949494 10.        ]
 [15.62049935 13.45362405 13.15294644]
 [19.20937271 17.02938637 16.4924225 ]
 [26.17250466 24.04163056 22.36067977]
 [35.4682957  33.30165161 31.76476035]
 [42.52058325 40.36087214 38.58756276]]
Clusters Array:  [[(2, 3)], [(3, 5), (5, 8), (10, 12)], [(12, 15), (14, 18), (20, 22), (25, 30), (30, 35)]]
cluster:  [(2, 3)]
cluster:  [(3, 5), (5, 8), (10, 12)]
cluster:  [(12, 15), (14, 18), (20, 22), (25, 30), (30, 35)]
newcent:  [(2.0, 3.0), (6.0, 8.333333333333334), (20.2, 24.0)]
oldcent:  [(2.0, 3.0), (6.0, 8.333333333333334), (20.2, 24.0)]
Distance:  [[ 0.          6.66666667 27.78920654]
 [ 2.23606798  4.48454135 25.62888995]
 [ 5.83095189  1.05409255 22.06898