<a href="https://colab.research.google.com/github/devdattatemgire/Data-Mining-Algorithms-/blob/main/DBSCAN/DBSCAN_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import statistics
import itertools
import math

In [ ]:
n = int(input('Enter the length of dataset: '))
dist = np.zeros(shape=(n,n))
print(dist)

Enter the length of dataset: 8
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
D =  [(2, 0), (2, 5), (8,4), (5, 8), (7, 5), (6, 4), (1, 2), (4, 9)]

In [ ]:
epsilon = 2
min_pts = 2
border = 1

In [ ]:
for i in range(int(len(D))):
        for j in range(int(len(D))):
            dist[i, j] = math.dist(D[i],D[j])


In [ ]:
dist

array([[0.        , 5.        , 7.21110255, 8.54400375, 7.07106781,
        5.65685425, 2.23606798, 9.21954446],
       [5.        , 0.        , 6.08276253, 4.24264069, 5.        ,
        4.12310563, 3.16227766, 4.47213595],
       [7.21110255, 6.08276253, 0.        , 5.        , 1.41421356,
        2.        , 7.28010989, 6.40312424],
       [8.54400375, 4.24264069, 5.        , 0.        , 3.60555128,
        4.12310563, 7.21110255, 1.41421356],
       [7.07106781, 5.        , 1.41421356, 3.60555128, 0.        ,
        1.41421356, 6.70820393, 5.        ],
       [5.65685425, 4.12310563, 2.        , 4.12310563, 1.41421356,
        0.        , 5.38516481, 5.38516481],
       [2.23606798, 3.16227766, 7.28010989, 7.21110255, 6.70820393,
        5.38516481, 0.        , 7.61577311],
       [9.21954446, 4.47213595, 6.40312424, 1.41421356, 5.        ,
        5.38516481, 7.61577311, 0.        ]])

In [ ]:
index_dict = {str('P'+ str(key)): [] for key in range(n)}
print(index_dict)

{'P0': [], 'P1': [], 'P2': [], 'P3': [], 'P4': [], 'P5': [], 'P6': [], 'P7': []}


In [ ]:
dict_ans = {str('P'+ str(key)): [] for key in range(n)}
print(dict_ans)

{'P0': [], 'P1': [], 'P2': [], 'P3': [], 'P4': [], 'P5': [], 'P6': [], 'P7': []}


In [ ]:
for i in range(n):
  for j in range(n):
    if j==i:
      continue
    else:
      if dist[i,j] <= epsilon:
        dict_ans[str('P'+ str(i))].append(str('P'+ str(j)))

In [ ]:
print(dict_ans)

{'P0': [], 'P1': [], 'P2': ['P4', 'P5'], 'P3': ['P7'], 'P4': ['P2', 'P5'], 'P5': ['P2', 'P4'], 'P6': [], 'P7': ['P3']}


In [ ]:
for key,value in dict_ans.items():
  if len(value) >= min_pts:
    index_dict[key].append('Core')
  elif len(value) == border:
    index_dict[key].append('Border')
  else:
    index_dict[key].append('Noise')


In [ ]:
index_dict

{'P0': ['Noise'],
 'P1': ['Noise'],
 'P2': ['Core'],
 'P3': ['Border'],
 'P4': ['Core'],
 'P5': ['Core'],
 'P6': ['Noise'],
 'P7': ['Border']}