<a href="https://colab.research.google.com/github/devdattatemgire/Data-Mining-Algorithms-/blob/main/Naive%20Bayes/Naive_Bayes_Classifier_EXPT_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import CSV

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/car.csv')
df_copy = df
print(len(df))

10


In [ ]:
print(df_copy.head())

   CAR NO   COLOR    TYPE    ORIGIN STOLEN
0       1     RED  SPORTS  DOMESTIC    YES
1       2     RED  SPORTS  DOMESTIC     NO
2       3     RED  SPORTS  DOMESTIC    YES
3       4  YELLOW  SPORTS  DOMESTIC     NO
4       5  YELLOW  SPORTS  IMPORTED    YES


In [ ]:
print(df)

   CAR NO   COLOR    TYPE    ORIGIN STOLEN
0       1     RED  SPORTS  DOMESTIC    YES
1       2     RED  SPORTS  DOMESTIC     NO
2       3     RED  SPORTS  DOMESTIC    YES
3       4  YELLOW  SPORTS  DOMESTIC     NO
4       5  YELLOW  SPORTS  IMPORTED    YES
5       6  YELLOW     SUV  IMPORTED     NO
6       7  YELLOW     SUV  IMPORTED    YES
7       8  YELLOW     SUV  DOMESTIC     NO
8       9     RED     SUV  IMPORTED     NO
9      10     RED  SPORTS  IMPORTED    YES


#Creating feature and lable data frames

In [ ]:
X = df.drop(df.columns[[0,-1]], axis = 1)
y = df.iloc[:,-1:]

In [ ]:
print(X.head())


    COLOR    TYPE    ORIGIN
0     RED  SPORTS  DOMESTIC
1     RED  SPORTS  DOMESTIC
2     RED  SPORTS  DOMESTIC
3  YELLOW  SPORTS  DOMESTIC
4  YELLOW  SPORTS  IMPORTED


#Creating list of Feature attributes and Label attributes

In [ ]:
# iterating the columns
label_attr = []
feature_attr = []
for col in y.columns:
    label_attr.append(col)
print(label_attr)
for col in X.columns:
    feature_attr.append(col)
print(feature_attr)

['STOLEN']
['COLOR', 'TYPE', 'ORIGIN']


#Creating a list within list of unique values in all attributes to create a dictionary of values


In [ ]:

features = [[] for _ in range(len(feature_attr))]
labels = [[] for _ in range(len(label_attr)) ]

for m in range(len(X.columns)):
 for i, j in X.iterrows():
      pd.Series.tolist(j)
      # print(j[m])
      if j[m] not in features[m]:
       features[m].append(j[m])
print(features)

for m in range(len(y.columns)):
  for i, j in y.iterrows():
        # print(j)
        pd.Series.tolist(j)
        if j[m] not in labels[m]:
          labels[m].append(j[m])

print(labels)

[['RED', 'YELLOW'], ['SPORTS', 'SUV'], ['DOMESTIC', 'IMPORTED']]
[['YES', 'NO']]


#Creating Dictionary of all feature values and aassigning them a numeric values inorder to access them as per the user input

In [ ]:

feat_dict = {}
label_dict = {}
temp_index = 0
for m in range(len(X.columns)):
  for i in features[m]:
        feat_dict[i] = int(temp_index)
        temp_index = temp_index + 1


temp_index = 0
print(feat_dict)
for m in range(len(y.columns)):
  for i in labels[m]:
        label_dict[i] = int(temp_index)
        temp_index = temp_index + 1


print(label_dict)

{'RED': 0, 'YELLOW': 1, 'SPORTS': 2, 'SUV': 3, 'DOMESTIC': 4, 'IMPORTED': 5}
{'YES': 0, 'NO': 1}


#Creating list of label value counts and feature value counts for calculating prior probability and liklehood

In [ ]:
label_counts = []
feature_counts = []


for m,i in zip(range(len(y.columns)), label_attr):
    for j in labels[m]:
      label_counts.append(y[i].value_counts()[j])

print(label_counts)
# print(type(label_counts))


for m,i in zip(range(len(X.columns)),feature_attr):
  for j in features[m]:
    feature_counts.append(X[i].value_counts()[j])

print(feature_counts)
# print(type(feature_counts))



[5, 5]
[5, 5, 6, 4, 5, 5]


#Calculating Prior Probability

In [ ]:
prior_prob = []
for i in label_counts:
  temp_prob = i / df.shape[0]
  prior_prob.append(temp_prob)
print(prior_prob)

[0.5, 0.5]


In [ ]:
print(df.head())

   CAR NO   COLOR    TYPE    ORIGIN STOLEN
0       1     RED  SPORTS  DOMESTIC    YES
1       2     RED  SPORTS  DOMESTIC     NO
2       3     RED  SPORTS  DOMESTIC    YES
3       4  YELLOW  SPORTS  DOMESTIC     NO
4       5  YELLOW  SPORTS  IMPORTED    YES


#Creating list of feature and label combination counts
### For example: [ RED - YES , RED - NO, YELLOW - YES, YELLOW - NO,.............. ]

In [ ]:
import numpy as np
df = df_copy
lh = []
likelihood =  np.empty(shape=(int(len(label_dict)),int(len(feat_dict))))
column_drop = []
row_drop = []
print(likelihood)


for i in range(len(feat_dict)):

  for j in range(len(label_dict)):
    df = pd.read_csv('/content/drive/MyDrive/car.csv')
    temp_feat = list(feat_dict.keys())[list(feat_dict.values()).index(i)]
    temp_label = list(label_dict.keys())[list(label_dict.values()).index(j)]
    print(temp_feat+' '+ temp_label)

    column_drop = []
    row_drop = []
    print('Initial:  ',df.head(10))

    for column in df.columns:
      if temp_feat not in df[column].values and temp_label not in df[column].values :
        column_drop.append(column)
    df.drop(columns=column_drop, inplace=True)
    print("Head: ",df.head(10))


    for index, row in df.iterrows():

     if ((temp_label not in row.values or temp_label in row.values) and temp_feat not in row.values) or (temp_label not in row.values and temp_feat in row.values):
        row_drop.append(index)

    print(row_drop)
    df.drop(index=row_drop, inplace=True)
    print("Head2: ",df.head())
    row_count = df.shape[0]
    lh.append(row_count)
print(lh)













[[4.72751721e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]]
RED YES
Initial:      CAR NO   COLOR    TYPE    ORIGIN STOLEN
0       1     RED  SPORTS  DOMESTIC    YES
1       2     RED  SPORTS  DOMESTIC     NO
2       3     RED  SPORTS  DOMESTIC    YES
3       4  YELLOW  SPORTS  DOMESTIC     NO
4       5  YELLOW  SPORTS  IMPORTED    YES
5       6  YELLOW     SUV  IMPORTED     NO
6       7  YELLOW     SUV  IMPORTED    YES
7       8  YELLOW     SUV  DOMESTIC     NO
8       9     RED     SUV  IMPORTED     NO
9      10     RED  SPORTS  IMPORTED    YES
Head:      COLOR STOLEN
0     RED    YES
1     RED     NO
2     RED    YES
3  YELLOW     NO
4  YELLOW    YES
5  YELLOW     NO
6  YELLOW    YES
7  YELLOW     NO
8     RED     NO
9     RED    YES
[1, 3, 4, 5, 6, 7, 8]
Head2:    COLOR STOLEN
0   RED    YES
2   RED    YES
9   RED    YES
RED NO
Initial:      

<ipython-input-12-2452f1be0f3a>:23: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if temp_feat not in df[column].values and temp_label not in df[column].values :
<ipython-input-12-2452f1be0f3a>:23: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if temp_feat not in df[column].values and temp_label not in df[column].values :
<ipython-input-12-2452f1be0f3a>:23: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if temp_feat not in df[column].values and temp_label not in df[column].values :
<ipython-input-12-2452f1be0f3a>:23: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if temp_feat not in df[column].values and temp_label not in df[column].values :
<ipython-input-12-2452f1

#Calculating Likelihood and Creating Numpy array of the same

In [ ]:
import statistics
import math
probb =[]
print('lh: ',lh)
m = 0
for j in range(len(feat_dict)):

  for i in range(int(len(label_dict))):
      print('i: ', i)
      # dist[i, j] = abs(D[i] - oldcent[j])
      s = lh[m]/label_counts[i]
      probb.append(s)
      likelihood[i, j] = s
      likelihood[i, j] = lh[m]/label_counts[i]
      m = m+1


print("Distance: ", likelihood)
print('Prob: ', probb)

lh:  [3, 2, 2, 3, 4, 2, 1, 3, 2, 3, 3, 2]
i:  0
i:  1
i:  0
i:  1
i:  0
i:  1
i:  0
i:  1
i:  0
i:  1
i:  0
i:  1
Distance:  [[0.6 0.4 0.8 0.2 0.4 0.6]
 [0.4 0.6 0.4 0.6 0.6 0.4]]
Prob:  [0.6, 0.4, 0.4, 0.6, 0.8, 0.4, 0.2, 0.6, 0.4, 0.6, 0.6, 0.4]


In [ ]:
print(likelihood)

[[0.6 0.4 0.8 0.2 0.4 0.6]
 [0.4 0.6 0.4 0.6 0.6 0.4]]


#Taking input

In [ ]:
test = []
for _ in range(X.shape[1]):
  temp = input('Enter the feature: ')
  test.append(temp.upper())
print(test)


Enter the feature: yellow
Enter the feature: suv
Enter the feature: imported
['YELLOW', 'SUV', 'IMPORTED']


#Function to make final predictions based on user input

In [ ]:
def predict(test):
    ans = []

    for k,j in label_dict.items():
      print('j: ',j)
      print('//////////////////////////////////////////////////')
      ans_temp = 1
      for i in test:
        for key, value in feat_dict.items():
          # print(key, value)
          if key == i:
            i = value
            # print(i, likelihood[j,i])
            ans_temp = ans_temp * likelihood[j,i]
            print("ans_temp", ans_temp)
      for key, value in label_dict.items():
          if key == j:
            j = value
      # print("j: ", j)
      ans_temp = (ans_temp) * (prior_prob[(j)])
      ans.append(ans_temp)
    # print("ans: ", ans_temp)
    maxx = max(ans)
    max_index = ans.index(maxx)
    for key, value in label_dict.items():
          if value == max_index:
            final_ans = key
    print(ans)
    return final_ans






In [ ]:
prediction = predict(test)
print("Prediction: ",prediction)

j:  0
//////////////////////////////////////////////////
ans_temp 0.4
ans_temp 0.08000000000000002
ans_temp 0.04800000000000001
j:  1
//////////////////////////////////////////////////
ans_temp 0.6
ans_temp 0.36
ans_temp 0.144
[0.024000000000000004, 0.072]
Prediction:  NO


In [ ]:
# import csv

# # Dataset
# data = [
#     ["COLOR", "TYPE", "ORIGIN", "STOLEN"],
#     ["RED", "SPORTS", "DOMESTIC", "YES"],
#     ["RED", "SPORTS", "DOMESTIC", "NO"],
#     ["RED", "SPORTS", "DOMESTIC", "YES"],
#     ["YELLOW", "SPORTS", "DOMESTIC", "NO"],
#     ["YELLOW", "SPORTS", "IMPORTED", "YES"],
#     ["YELLOW", "SUV", "IMPORTED", "NO"],
#     ["YELLOW", "SUV", "IMPORTED", "YES"],
#     ["YELLOW", "SUV", "DOMESTIC", "NO"],
#     ["RED", "SUV", "IMPORTED", "NO"],
#     ["RED", "SPORTS", "IMPORTED", "YES"],
#     ["RED", "SUV", "DOMESTIC", "YES"],
#     ["YELLOW", "SPORTS", "DOMESTIC", "YES"],
#     ["YELLOW", "SUV", "DOMESTIC", "YES"],
#     ["RED", "SUV", "IMPORTED", "YES"],
#     ["YELLOW", "SPORTS", "IMPORTED", "NO"],
#     ["YELLOW", "SPORTS", "DOMESTIC", "YES"],
#     ["YELLOW", "SUV", "IMPORTED", "YES"],
#     ["RED", "SPORTS", "DOMESTIC", "NO"],
#     ["YELLOW", "SPORTS", "IMPORTED", "YES"],
#     ["RED", "SUV", "DOMESTIC", "YES"],
#     ["YELLOW", "SPORTS", "DOMESTIC", "YES"],
#     ["RED", "SPORTS", "IMPORTED", "NO"],
#     ["YELLOW", "SUV", "DOMESTIC", "NO"],
#     ["RED", "SUV", "DOMESTIC", "YES"],
#     ["YELLOW", "SPORTS", "IMPORTED", "YES"],
#     ["RED", "SPORTS", "DOMESTIC", "NO"],
#     ["YELLOW", "SPORTS", "DOMESTIC", "YES"],
#     ["RED", "SUV", "IMPORTED", "YES"],
#     ["YELLOW", "SUV", "DOMESTIC", "NO"],
#     ["RED", "SPORTS", "IMPORTED", "NO"],
#     ["YELLOW", "SPORTS", "DOMESTIC", "YES"],
#     ["RED", "SUV", "DOMESTIC", "YES"],
#     ["YELLOW", "SPORTS", "IMPORTED", "YES"],
#     ["RED", "SPORTS", "DOMESTIC", "NO"],
#     ["YELLOW", "SUV", "IMPORTED", "NO"],
#     ["RED", "SPORTS", "IMPORTED", "YES"],
# ]

# # File path
# file_path = "car2.csv"

# # Save the data to a CSV file
# with open(file_path, "w", newline="") as csv_file:
#     writer = csv.writer(csv_file)
#     writer.writerows(data)

# print(f"Dataset saved to {file_path}")


In [ ]:
#Creting list within list of unique value

# features = []
# labels = []


# for i, j in X.iterrows():
#    for m in range(len(X.columns)):
#       pd.Series.tolist(j)
#       # print(j[m])
#       if j[m] not in features:
#        features.append(j[m])
# print(features)


# for i, j in y.iterrows():
#     for m in range(len(y.columns)):
#       # print(j)
#       pd.Series.tolist(j)
#       if j[m] not in labels:
#         labels.append(j[m])

# print(labels)

In [ ]:
#Creating Dictionary

# feat_dict = {}
# label_dict = {}

# # for m in range(len(X.columns)):
# for i,j in zip(features,range(len(features))):
#       feat_dict[i] = j


# print(feat_dict)
# # for m in range(len(y.columns)):
# for i,j in zip(labels,range(len(labels))):
#       label_dict[i] = j

# print(label_dict)

