<a href="https://colab.research.google.com/github/devdattatemgire/Data-Mining-Algorithms-/blob/main/Agglomeretive%20Clustering/Aglomeretive_EXPT_4_Clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import statistics

In [ ]:
n = int(input('Enter the length of dataset: '))
dist = np.zeros(shape=(n,n))
print(dist)

Enter the length of dataset: 5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
index_dict = {key: [key] for key in range(n)}
print(index_dict)
index_dict_ans = {key: [str('P'+ str(key))] for key in range(n)}
print(index_dict_ans)

{0: [0], 1: [1], 2: [2], 3: [3], 4: [4]}
{0: ['P0'], 1: ['P1'], 2: ['P2'], 3: ['P3'], 4: ['P4']}


In [ ]:
for i in range(n):
  print(i)
  for j in range(i+1):
    dist[i,j] = float(input("Enter the element"))
print(dist)

In [ ]:
dist = np.array([
    [0, 0, 0, 0, 0],
    [9, 0, 0, 0, 0],
    [3, 7, 0, 0, 0],
    [6, 5, 9, 0, 0],
    [11, 10, 2, 8, 0]
])

# dist = np.array([
#     [0, 0, 0, 0, 0, 0],
#     [0.23, 0, 0, 0, 0, 0],
#     [0.22, 0.14, 0, 0, 0, 0],
#     [0.37, 0.19, 0.13, 0, 0, 0],
#     [0.34, 0.14, 0.28, 0.23, 0, 0],
#     [0.24, 0.24, 0.10, 0.22, 0.39, 0]
# ])



print(dist)

[[ 0  0  0  0  0]
 [ 9  0  0  0  0]
 [ 3  7  0  0  0]
 [ 6  5  9  0  0]
 [11 10  2  8  0]]


In [ ]:
m = 0
final_pattern = []
final_pattern_ans = []

In [ ]:
while(n!=1):

  min_list = []
  for i in range(1,n):
    for j in range(i):
      min_list.append(dist[i,j])
  print(min_list)
  min = np.min(min_list)
  print(min)

  merge_index = np.where(dist == min)
  print(merge_index)
  list_of_index = list(zip(merge_index[0],merge_index[1]))
  for index in list_of_index:
    print("Index: ",index)
  index = list(index)
  print(index)

  index_dict[np.min(index)].append(np.max(index))
  print('test', final_pattern)
  print('dicty: ', index_dict[np.min(index)])
  final_pattern.append(index_dict[np.min(index)].copy())
  # final_pattern.append(index_dict[np.min(index)])
  for k in index_dict_ans[np.max(index)]:
   index_dict_ans[np.min(index)].append(k)
   # index_dict_ans[np.min(index)] = index_dict_ans[np.min(index)] + index_dict_ans[np.max(index)]
  final_pattern_ans.append(index_dict_ans[np.min(index)].copy())
  # final_pattern_ans.append(index_dict_ans[np.min(index)])

  index_dict.pop(np.max(index))
  index_dict_ans.pop(np.max(index))

  temp_val_list = list(index_dict.values())
  temp_val_list_ans = list(index_dict_ans.values())
  n=n-1
  index_dict_new = {key: temp_val_list[i] for i, key in enumerate(range(n))}
  index_dict_ans_new ={key: temp_val_list_ans[i] for i, key in enumerate(range(n))}

  index_dict = index_dict_new
  index_dict_ans = index_dict_ans_new

  new_dist = np.zeros(shape=(n,n))
  for i in range(n):
    for j in range(i+1):
      new_dist[i,j]=dist[i,j]
  print(new_dist)
  key_list=list(index_dict.keys())
  val_list=list(index_dict.values())
  ind=val_list.index(final_pattern[m])

  k = key_list[ind]
  for i in range(k):
    # new_dist[k,i] = np.min([dist[s,i] for s in final_pattern[m]])
    new_dist[k,i] = np.min([dist[s,i] for s in index])
  # if (np.max(index) != n-1):
  for i in range(np.max(index),n):
    for j in range(n):
      new_dist[i,j] = dist[i+1,j]

  for i in range(n):
    new_dist[i,i]=0
  m = m + 1
  dist = new_dist

print('Final Answer: ', final_pattern_ans)

[9, 3, 7, 6, 5, 9, 11, 10, 2, 8]
2
(array([4]), array([2]))
Index:  (4, 2)
[4, 2]
test []
dicty:  [2, 4]
[[0. 0. 0. 0.]
 [9. 0. 0. 0.]
 [3. 7. 0. 0.]
 [6. 5. 9. 0.]]
[9.0, 3.0, 7.0, 6.0, 5.0, 9.0]
3.0
(array([2]), array([0]))
Index:  (2, 0)
[2, 0]
test [[2, 4]]
dicty:  [0, 2]
[[0. 0. 0.]
 [9. 0. 0.]
 [3. 7. 0.]]
[9.0, 6.0, 5.0]
5.0
(array([2]), array([1]))
Index:  (2, 1)
[2, 1]
test [[2, 4], [0, 2]]
dicty:  [1, 2]
[[0. 0.]
 [9. 0.]]
[6.0]
6.0
(array([1]), array([0]))
Index:  (1, 0)
[1, 0]
test [[2, 4], [0, 2], [1, 2]]
dicty:  [0, 2, 1]
[[0.]]
Final Answer:  [['P2', 'P4'], ['P0', 'P2', 'P4'], ['P1', 'P3'], ['P0', 'P2', 'P4', 'P1', 'P3']]


In [ ]:
type( index )

list